version: '3.4'

networks:
  gmaa-server-network:
    driver: bridge

services:
  redis_db:
    networks:
      - gmaa-server-network
    image: redis:6.2
    expose:
      - 6379

  app:
    networks:
      - gmaa-server-network
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - redis_db
    ports:
      - 8000:8000
    environment:
      LOGGER_LEVEL: 'debug'
      GIPHY_URL: ${GIPHY_URL}
      GIPHY_TOKEN: ${GIPHY_TOKEN}
      REDIS_URL: 'redis://redis_db'
